CREATE_LEAD = 'create_lead'
CREATE_CONTACT = 'create_contact'
CREATE_ACCOUNT = 'create_account'
CREATE_CASE = 'create_case'
CREATE_EVENT = 'create_event'
CREATE_TASK = 'create_task'
CREATE_OPPORTUNITY = 'create_opportunity'
ALL = 'ALL'

ALL_ACTIONS = [CREATE_LEAD, CREATE_TASK, CREATE_ACCOUNT, CREATE_EVENT, CREATE_OPPORTUNITY, CREATE_CASE]

limit_rate = {
    CREATE_LEAD: 1000,
    CREATE_CONTACT: 1000,
    CREATE_ACCOUNT: 1000,
    CREATE_CASE: 1000,
    CREATE_EVENT: 1000,
    CREATE_TASK: 1000,
    CREATE_OPPORTUNITY: 1000,
    ALL: 5000
}
